### ISSUE TITLE
OpenAPI: response 200 for /generate is wrong

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/server-api#34]
#### Describe the bug
It says a 200 response is application/json: https://github.com/asyncapi/server-api/blob/master/openapi.yaml#L41

#### Expected behavior
It should instead be:

```yaml
application/octet-stream:
  schema:
    type: string
    format: binary
```
